"""Pinned trusted setup for isolated channel conformance scenarios.

This configuration is reviewed with the harness, outside presented vectors.
Each named test is an independent verifier lifetime. It is not a production
issuer, persisted replay store, or authority derived from received metadata.
"""

TRUSTED_CONTEXTS = {'canonical-algorithm-key-confusion': {'lastSequence': 0,
                                       'priorChannelIds': ['channel-100', 'channel-200'],
                                       'sessionChannelId': 'channel-349'},
 'canonical-boolean-replies-to': {'lastSequence': 0,
                                  'priorChannelIds': ['channel-100', 'channel-200'],
                                  'sessionChannelId': 'channel-349'},
 'canonical-boolean-sequence': {'lastSequence': 0,
                                'priorChannelIds': ['channel-100', 'channel-200'],
                                'sessionChannelId': 'channel-349'},
 'canonical-decreasing-sequence': {'lastSequence': 4,
                                   'priorChannelIds': ['channel-100', 'channel-200'],
                                   'sessionChannelId': 'channel-349'},
 'canonical-duplicate-sequence': {'lastSequence': 3,
                                  'priorChannelIds': ['channel-100', 'channel-200'],
                                  'sessionChannelId': 'channel-349'},
 'canonical-ecdsa-cross-domain': {'lastSequence': 1,
                                  'priorChannelIds': ['channel-100', 'channel-200'],
                                  'sessionChannelId': 'channel-349'},
 'canonical-ecdsa-raw-digest-framing': {'lastSequence': 1,
                                        'priorChannelIds': ['channel-100', 'channel-200'],
                                        'sessionChannelId': 'channel-349'},
 'canonical-ecdsa-tampered-body': {'lastSequence': 1,
                                   'priorChannelIds': ['channel-100', 'channel-200'],
                                   'sessionChannelId': 'channel-349'},
 'canonical-ecdsa-valid': {'lastSequence': 1,
                           'priorChannelIds': ['channel-100', 'channel-200'],
                           'sessionChannelId': 'channel-349'},
 'canonical-empty-channel-id': {'lastSequence': 0,
                                'priorChannelIds': ['channel-100', 'channel-200'],
                                'sessionChannelId': 'channel-349'},
 'canonical-empty-refs-object': {'lastSequence': 0,
                                 'priorChannelIds': ['channel-100', 'channel-200'],
                                 'sessionChannelId': 'channel-349'},
 'canonical-foreign-channel': {'lastSequence': 0,
                               'priorChannelIds': ['channel-100', 'channel-200'],
                               'sessionChannelId': 'channel-349'},
 'canonical-hex-signature-value': {'lastSequence': 0,
                                   'priorChannelIds': ['channel-100', 'channel-200'],
                                   'sessionChannelId': 'channel-349'},
 'canonical-member-wrong-key': {'lastSequence': 1,
                                'priorChannelIds': ['channel-100', 'channel-200'],
                                'sessionChannelId': 'channel-349'},
 'canonical-missing-signature': {'lastSequence': 0,
                                 'priorChannelIds': ['channel-100', 'channel-200'],
                                 'sessionChannelId': 'channel-349'},
 'canonical-open-signature-envelope': {'lastSequence': 0,
                                       'priorChannelIds': ['channel-100', 'channel-200'],
                                       'sessionChannelId': 'channel-349'},
 'canonical-outsider-valid-signature': {'lastSequence': 1,
                                        'priorChannelIds': ['channel-100', 'channel-200'],
                                        'sessionChannelId': 'channel-349'},
 'canonical-padded-base64url': {'lastSequence': 0,
                                'priorChannelIds': ['channel-100', 'channel-200'],
                                'sessionChannelId': 'channel-349'},
 'canonical-preserve-unknown-signed-field': {'lastSequence': 0,
                                             'priorChannelIds': ['channel-100', 'channel-200'],
                                             'sessionChannelId': 'channel-349'},
 'canonical-qualified-member-identity': {'lastSequence': 1,
                                         'priorChannelIds': ['channel-100', 'channel-200'],
                                         'sessionChannelId': 'channel-349'},
 'canonical-reused-session-channel': {'lastSequence': 0,
                                      'priorChannelIds': ['channel-reused'],
                                      'sessionChannelId': 'channel-reused'},
 'canonical-signer-sender-mismatch': {'lastSequence': 0,
                                      'priorChannelIds': ['channel-100', 'channel-200'],
                                      'sessionChannelId': 'channel-349'},
 'canonical-sr1-aggregate-cross-domain': {'lastSequence': 2,
                                          'priorChannelIds': ['channel-100', 'channel-200'],
                                          'sessionChannelId': 'channel-349'},
 'canonical-sr1-aggregate-raw-digest-framing': {'lastSequence': 2,
                                                'priorChannelIds': ['channel-100', 'channel-200'],
                                                'sessionChannelId': 'channel-349'},
 'canonical-sr1-aggregate-tampered-body': {'lastSequence': 2,
                                           'priorChannelIds': ['channel-100', 'channel-200'],
                                           'sessionChannelId': 'channel-349'},
 'canonical-sr1-aggregate-valid': {'lastSequence': 2,
                                   'priorChannelIds': ['channel-100', 'channel-200'],
                                   'sessionChannelId': 'channel-349'},
 'canonical-standard-base64-character': {'lastSequence': 0,
                                         'priorChannelIds': ['channel-100', 'channel-200'],
                                         'sessionChannelId': 'channel-349'},
 'canonical-stripped-unknown-field': {'lastSequence': 0,
                                      'priorChannelIds': ['channel-100', 'channel-200'],
                                      'sessionChannelId': 'channel-349'},
 'canonical-tampered-body': {'lastSequence': 0,
                             'priorChannelIds': ['channel-100', 'channel-200'],
                             'sessionChannelId': 'channel-349'},
 'canonical-unknown-algorithm': {'lastSequence': 0,
                                 'priorChannelIds': ['channel-100', 'channel-200'],
                                 'sessionChannelId': 'channel-349'},
 'canonical-unknown-message-version': {'lastSequence': 0,
                                       'priorChannelIds': ['channel-100', 'channel-200'],
                                       'sessionChannelId': 'channel-349'},
 'canonical-unknown-signature-version': {'lastSequence': 0,
                                         'priorChannelIds': ['channel-100', 'channel-200'],
                                         'sessionChannelId': 'channel-349'},
 'canonical-unresolved-sender': {'lastSequence': 0,
                                 'priorChannelIds': ['channel-100', 'channel-200'],
                                 'sessionChannelId': 'channel-349'},
 'canonical-valid-first': {'lastSequence': 0,
                           'priorChannelIds': ['channel-100', 'channel-200'],
                           'sessionChannelId': 'channel-349'},
 'canonical-valid-next': {'lastSequence': 1,
                          'priorChannelIds': ['channel-100', 'channel-200'],
                          'sessionChannelId': 'channel-349'},
 'canonical-valid-sequence-gap': {'lastSequence': 2,
                                  'priorChannelIds': ['channel-100', 'channel-200'],
                                  'sessionChannelId': 'channel-349'},
 'ch6-channelId-reused': {'lastSequence': 0,
                          'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                          'sessionChannelId': 'chan-session-1'},
 'cross-domain-current-to-legacy': {'lastSequence': 0,
                                    'priorChannelIds': ['channel-100', 'channel-200'],
                                    'sessionChannelId': 'channel-349'},
 'cross-domain-legacy-to-current': {'lastSequence': 0,
                                    'priorChannelIds': ['channel-100', 'channel-200'],
                                    'sessionChannelId': 'channel-349'},
 'ctx-fractional-lastSequence': {'lastSequence': 1.5,
                                 'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                 'sessionChannelId': 'chan-session-7'},
 'ctx-priorChannelIds-bad-element': {'lastSequence': 0,
                                     'priorChannelIds': [123],
                                     'sessionChannelId': 'chan-session-7'},
 'foreign-channel-message': {'lastSequence': 0,
                             'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                             'sessionChannelId': 'chan-session-7'},
 'legacy-byte-preserving-read-only-import': {'lastSequence': 0,
                                             'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                             'sessionChannelId': 'chan-session-7'},
 'legacy-uppercase-hex-rejected': {'lastSequence': 0,
                                   'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                   'sessionChannelId': 'chan-session-7'},
 'malformed-context-boolean-sequence': {'lastSequence': True,
                                        'priorChannelIds': ['channel-100', 'channel-200'],
                                        'sessionChannelId': 'channel-349'},
 'malformed-missing-channelId': {'lastSequence': 0,
                                 'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                 'sessionChannelId': 'chan-session-7'},
 'mixed-current-discriminator-legacy-signature': {'lastSequence': 0,
                                                  'priorChannelIds': ['channel-100', 'channel-200'],
                                                  'sessionChannelId': 'channel-349'},
 'mixed-current-raw-digest-framing': {'lastSequence': 0,
                                      'priorChannelIds': ['channel-100', 'channel-200'],
                                      'sessionChannelId': 'channel-349'},
 'mixed-legacy-hex-digest-framing': {'lastSequence': 0,
                                     'priorChannelIds': ['channel-100', 'channel-200'],
                                     'sessionChannelId': 'channel-349'},
 'neither-selector-no-discriminator-current-envelope': {'lastSequence': 0,
                                                        'priorChannelIds': ['channel-100', 'channel-200'],
                                                        'sessionChannelId': 'channel-349'},
 'rechannelled-message-sig-breaks': {'lastSequence': 0,
                                     'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                     'sessionChannelId': 'chan-session-7'},
 'replay-decreasing-sequence': {'lastSequence': 5,
                                'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                'sessionChannelId': 'chan-session-7'},
 'replay-duplicate-sequence': {'lastSequence': 3,
                               'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                               'sessionChannelId': 'chan-session-7'},
 'sender-not-cci': {'lastSequence': 0,
                    'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                    'sessionChannelId': 'chan-session-7'},
 'sequence-below-one': {'lastSequence': 0,
                        'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                        'sessionChannelId': 'chan-session-7'},
 'tampered-body-after-signing': {'lastSequence': 0,
                                 'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                                 'sessionChannelId': 'chan-session-7'},
 'tampered-signature': {'lastSequence': 0,
                        'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                        'sessionChannelId': 'chan-session-7'},
 'untrusted-context-membership-injection': {'authenticatedMembers': [{'algorithm': 'ed25519',
                                                                      'claim': 'cci:e70a5bcf97758337d7191df8e32ddd310933ce077937e36723b8b3be4dd69f57',
                                                                      'publicKey': 'ea0c2afe8504c5500e1c28d05d4a2f214c076c8fc2c0db3225d13d1c1513d693'}],
                                            'lastSequence': 0,
                                            'priorChannelIds': ['channel-100', 'channel-200'],
                                            'sessionChannelId': 'channel-349'},
 'valid-first-message': {'lastSequence': 0,
                         'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                         'sessionChannelId': 'chan-session-7'},
 'valid-next-message': {'lastSequence': 1,
                        'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                        'sessionChannelId': 'chan-session-7'},
 'valid-sequence-gap': {'lastSequence': 2,
                        'priorChannelIds': ['chan-session-1', 'chan-session-2'],
                        'sessionChannelId': 'chan-session-7'}}
