#!/usr/bin/env python3
"""Deterministic (re)generator for conformance/vectors/security/bundle-binding-v0.1.json.

Reshapes every anchored bundle to the DACS-5 v0.3 ``FaultAttestationBundle`` type
(``faultBundleVersion: "1"``, no ``bundleVersion``), re-derives each
``attestation_bundle_hash``, re-signs every bundle signature under the
``dacs-fault-bundle:v1:`` domain and every BundleBinding signature under
``dacs-bundle-binding:v1:`` (CORE §B.7), and applies the §10.4.2 BB-6/BB-7
L2 semantics to the multiplicity vectors (7 renamed to
``bb-equal-standing-divergence`` and 8 changed to ``indeterminate`` — budget
exhaustion and equal-standing authorized divergence are ``indeterminate``,
never a void or an ``error`` classification). It also upgrades each nested
agreement reference to the normative DACS-2 §7.5.2 ``AttestationRef`` wire
shape; this changes the signed bundle bytes and is therefore part of the same
deterministic regeneration (#308).

The transform is a fixed point: applied to its own output it yields identical
bytes, so ``--write`` then ``--check`` is a determinism proof. Buyer/seller
seeds are the repo's public test seeds; ed25519 signing is deterministic.

Usage:
  python3 scripts/generate_bundle_binding_vectors.py --write   # emit the file
  python3 scripts/generate_bundle_binding_vectors.py --check   # regen in memory, byte-compare (exit 1 on mismatch)
"""
import argparse
import base64
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VECTOR_PATH = ROOT / "conformance" / "vectors" / "security" / "bundle-binding-v0.1.json"

# Public test seeds (already published in the vector header); ed25519 private-key seeds.
SEEDS = {
    "buyer": "a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1a1",
    "seller": "c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3",
}
ROLE_BY_CLAIM = {"did:demos:buyer": "buyer", "did:demos:seller": "seller"}
BUNDLE_DOMAIN = "dacs-fault-bundle:v1:"
BINDING_DOMAIN = "dacs-bundle-binding:v1:"

# Provenance strings (the synthetic-listingRef sentence is preserved verbatim from the
# pre-regeneration header).
PROV_GENERATOR = (
    "scripts/generate_bundle_binding_vectors.py (deterministic; reuses the repo "
    "buyer/seller test seeds)"
)
PROV_CANON = (
    "RFC 8785 JCS over the artifact minus its hash-excluded fields "
    "(FaultAttestationBundle: signatures+anchoredByRole; binding: signature); "
    "attestation_bundle_hash = sha256 hex; signatures ed25519 over the CORE §B.7 "
    "domain-separated payload (dacs-fault-bundle:v1: / dacs-bundle-binding:v1: || hash), "
    "base64url-unpadded. Regenerated deterministically by "
    "scripts/generate_bundle_binding_vectors.py (--check is a byte-for-byte determinism proof)."
)
PROV_NOTE = (
    "candidate tier — awaiting a second-impl cross-run per CROSS-RUN.md. Regenerated by "
    "scripts/generate_bundle_binding_vectors.py: bundles reshaped to the "
    "FaultAttestationBundle type (the type's version discriminator replaces the legacy per-bundle "
    "version literal) and re-signed under dacs-fault-bundle:v1:; the §10.4.2 BB-6/BB-7 L2 model "
    "updates vectors 7–8 — vector 7 (the former equal-standing-void case) is renamed to "
    "bb-equal-standing-divergence (fail → indeterminate) and vector 8 bb-multiplicity-limit "
    "changed error → indeterminate, since "
    "equal-standing authorized divergence and budget exhaustion are indeterminate, never a void or "
    "a classification."
)
PROV_LISTINGREF = (
    "Each vector's listingRef.contentHash is synthetic (sha256(\"listing-\" + jobId)), not "
    "pinned to a real listing — the listing is not the subject of these resolution vectors."
)
DECISION_MODEL = (
    "Resolve a side's native bundle address through published BundleBindings. Order: BB-4 "
    "signature/signer verify; BB-5 reject-on-any over the signed tuple (bindingVersion "
    "supported, jobId/role == requested, logicalAddress == derive(signed jobId, role), fetched "
    "jobId == binding.jobId, byte-exact §10.4.1 attestation_bundle_hash, signer holds role, "
    "§10.4.1 faultedParty within the permissible set for (outcome, anchoredByRole)); group the "
    "BB-4-valid candidates by authenticated signer and prune to the co-signed party map where "
    "available; fetch at most N=8 in ascending bundleContentHash order; among authorized copies "
    "collapse canonically-equal, apply full-signature precedence, and treat equal-standing "
    "divergence as indeterminate (BB-6); BB-7 fail-closed. Dispositions: a resolved+valid binding "
    "to a present copy is present (pass); a present-but-invalid binding is fail; total "
    "non-resolution, budget exhaustion, or equal-standing authorized divergence is indeterminate; "
    "authoritative absent requires the CORE §5 absence-evidence policy."
)

# Per-index semantic overrides (stable across runs — keyed by position, not by name, so the
# vector-7 rename is idempotent).
NAME_OVERRIDES = {7: "bb-equal-standing-divergence"}
EXPECTED_OVERRIDES = {7: "indeterminate", 8: "indeterminate"}
REASON_OVERRIDES = {
    4: (
        "declared faultedParty is outside the §10.4.1 permissible set for "
        "(outcome=aborted-by-other, anchoredByRole=seller) — the permissible value is any party "
        "role other than seller (buyer here); the cross-role rebind is rejected (BB-5), so it "
        "cannot silently reverse blame"
    ),
    5: (
        "no BB-4-valid binding resolves for the requested (jobId, role); the side's §10.4.3 read "
        "disposition is indeterminate — neither present nor authoritatively absent (BB-7)"
    ),
    6: (
        "BB-6 full-signature precedence among authorized copies: the co-signed completed copy is "
        "retained over the single-signed divergent; both copies are seller-authorized"
    ),
    7: (
        "two equal-standing single-signed authorized copies diverge on the absolute faultedParty "
        "(seller vs buyer); BB-6 selects neither and the side's read disposition is indeterminate "
        "(BB-7) — the session is excluded from reputation, not blamed; there is no void"
    ),
    8: (
        "nine authorized bindings exceed the BB-6 fetch budget N=8; budget exhaustion yields the "
        "side disposition indeterminate, never a classification — a consumer MAY re-run resolution "
        "with a larger budget"
    ),
}
# Vector 3's binding declares a deterministic wrong content hash (intentional BB-5.8 mismatch).
def mismatch_hash(job_id):
    return hashlib.sha256(("mismatch:" + job_id).encode("utf-8")).hexdigest()


def _signing_keys():
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    return {r: Ed25519PrivateKey.from_private_bytes(bytes.fromhex(s)) for r, s in SEEDS.items()}


def canonical(value):
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def b64u(raw):
    return base64.urlsafe_b64encode(raw).rstrip(b"=").decode("ascii")


def bundle_hash(bundle):
    unsigned = {k: v for k, v in bundle.items() if k not in ("signatures", "anchoredByRole")}
    return hashlib.sha256(canonical(unsigned)).hexdigest()


def binding_hash(binding):
    unsigned = {k: v for k, v in binding.items() if k != "signature"}
    return hashlib.sha256(canonical(unsigned)).hexdigest()


def reshape_bundle(bundle, keys):
    """Return a new bundle dict with bundleVersion replaced by faultBundleVersion in place."""
    out = {}
    for k, v in bundle.items():
        if k == "bundleVersion":
            out["faultBundleVersion"] = "1"
        elif k == "faultBundleVersion":
            out["faultBundleVersion"] = "1"
        else:
            out[k] = v
    if "faultBundleVersion" not in out:  # bundle had neither key (shouldn't happen)
        out = {"faultBundleVersion": "1", **out}
    agreement_ref = out.get("agreementRef")
    if (
        isinstance(agreement_ref, dict)
        and "anchor" not in agreement_ref
        and isinstance(agreement_ref.get("id"), str)
    ):
        out["agreementRef"] = {
            "anchor": {
                "kind": "storage-program",
                "locator": agreement_ref["id"],
            },
            "contentHash": agreement_ref["contentHash"],
        }
    return out


def transform(data, keys):
    original_native = _collect_native_addresses(data)
    for idx, vector in enumerate(data["vectors"]):
        # 1. Reshape + re-hash + re-sign every anchored bundle; remember each address's new hash.
        new_hash_by_addr = {}
        anchored = vector.get("anchored", {})
        for addr in list(anchored.keys()):
            bundle = reshape_bundle(anchored[addr], keys)
            h = bundle_hash(bundle)
            new_hash_by_addr[addr] = h
            payload = (BUNDLE_DOMAIN + h).encode("utf-8")
            for sig in bundle.get("signatures", []):
                role = ROLE_BY_CLAIM[sig["party"]]
                sig["value"] = b64u(keys[role].sign(payload))
            anchored[addr] = bundle

        # 2. Re-derive each binding's bundleContentHash + signature.
        for bidx, binding in enumerate(vector.get("bindings", [])):
            addr = binding.get("nativeAddress")
            if idx == 3:
                # bb-content-hash-mismatch: keep a deterministic wrong content hash.
                binding["bundleContentHash"] = mismatch_hash(binding["jobId"])
            elif addr in new_hash_by_addr:
                binding["bundleContentHash"] = new_hash_by_addr[addr]
            bh = binding_hash(binding)
            payload = (BINDING_DOMAIN + bh).encode("utf-8")
            signer_role = ROLE_BY_CLAIM[binding["signature"]["signer"]]
            if idx == 1:
                # bb-invalid-binding-sig: sign with the WRONG key so BB-4 fails against the
                # declared signer's public key (deterministic invalid signature).
                wrong = "buyer" if signer_role == "seller" else "seller"
                binding["signature"]["value"] = b64u(keys[wrong].sign(payload))
            else:
                binding["signature"]["value"] = b64u(keys[signer_role].sign(payload))

        # 3. Scrub any legacy per-vector note that still names the old bundle-version model.
        if "note" in vector:
            vector["note"] = vector["note"].replace(
                'bundleVersion "2"', "FaultAttestationBundle"
            )

        # 4. Semantic want/name/expected overrides.
        if idx in NAME_OVERRIDES:
            vector["name"] = NAME_OVERRIDES[idx]
        if idx in EXPECTED_OVERRIDES:
            vector["expected"] = EXPECTED_OVERRIDES[idx]
            if "expected" in vector.get("want", {}):
                vector["want"]["expected"] = EXPECTED_OVERRIDES[idx]
        if idx in REASON_OVERRIDES and "reason" in vector.get("want", {}):
            vector["want"]["reason"] = REASON_OVERRIDES[idx]
        # vector 3: refresh the disclosed hashes in `want`.
        if idx == 3:
            b = vector["bindings"][0]
            addr = b["nativeAddress"]
            vector["want"]["actualBundleContentHash"] = new_hash_by_addr[addr]
            vector["want"]["bindingBundleContentHash"] = b["bundleContentHash"]
        # vector 0/6: refresh the disclosed resolved faultedParty stays "none" (unchanged);
        # want.resolvedNativeAddress is unchanged (native addresses are byte-preserved).

    # Native addresses must not change (write-input-derived, independent of bundle content).
    if _collect_native_addresses(data) != original_native:
        raise SystemExit("FATAL: a nativeAddress changed during reshape — write-input invariant broken")

    # Header.
    prov = data["provenance"]
    prov["generator"] = PROV_GENERATOR
    prov["canonicalisation"] = PROV_CANON
    prov["note"] = PROV_NOTE
    prov["listingRef"] = PROV_LISTINGREF
    data["decisionModel"] = DECISION_MODEL
    data["count"] = len(data["vectors"])
    data["hash"] = hashlib.sha256(
        json.dumps(data["vectors"], separators=(",", ":"), sort_keys=True, ensure_ascii=False).encode("utf-8")
    ).hexdigest()
    return data


def _collect_native_addresses(data):
    addrs = set()
    for vector in data["vectors"]:
        addrs.update(vector.get("anchored", {}).keys())
        for b in vector.get("bindings", []):
            if b.get("nativeAddress"):
                addrs.add(b["nativeAddress"])
    return addrs


def render(data):
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def main():
    ap = argparse.ArgumentParser()
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()

    keys = _signing_keys()
    source = json.loads(VECTOR_PATH.read_text(encoding="utf-8"))
    regenerated = render(transform(source, keys))

    if args.write:
        VECTOR_PATH.write_text(regenerated, encoding="utf-8")
        print(f"wrote {VECTOR_PATH.relative_to(ROOT)} ({len(regenerated)} bytes, "
              f"{len(json.loads(regenerated)['vectors'])} vectors)")
        return 0

    on_disk = VECTOR_PATH.read_text(encoding="utf-8")
    if on_disk == regenerated:
        print("bundle-binding vectors OK — file is byte-identical to a fresh regeneration")
        return 0
    print("MISMATCH: on-disk file differs from a fresh regeneration (run --write)")
    return 1


if __name__ == "__main__":
    sys.exit(main())
